spring:
  config:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    driver-class-name: org.postgresql.Driver
    username: ajay
    password: Ajay@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api


server:
    port: 8010


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

aws:
  region: ap-south-1

  secret:
    name: springboot/s3/credentials

  s3:
    enabled: true
    bucket: my-springboot-bucket-aj-123
